# docker-compose.yml

version: "3.9"

services:
  highstreet-ai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  highstreet-ai-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - highstreet-ai-backend
    restart: unless-stopped
